### ISSUE TITLE
multidimensionalPGMのコンパイルメッセージ

### ISSUE THREAD

**Issue by shiyunya** [dbgroup-nagoya-u/202104-PGMindex-suzuki#1]
#ifdef のための#defineを追加し，コンパイルしました
~~~
$ g++ examples/multidimensional.cpp -std=c++17 -I./include -o `multidimensional`
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/include/immintrin.h:105,
                 from ./include/pgm/morton_nd.hpp:41,
                 from ./include/pgm/pgm_index_variants.hpp:18,
                 from examples/multidimensional.cpp:15:
/usr/lib/gcc/x86_64-linux-gnu/9/include/bmi2intrin.h: In function ‘unsigned int _bzhi_u32(unsigned int, unsigned int)’:
/usr/lib/gcc/x86_64-linux-gnu/9/include/bmi2intrin.h:41:10: error: ‘__builtin_ia32_bzhi_si’ was not declared in this scope; did you mean ‘__builtin_ia32_bsrsi’?
   41 |   return __builtin_ia32_bzhi_si (__X, __Y);
      |          ^~~~~~~~~~~~~~~~~~~~~~
      |          __builtin_ia32_bsrsi
/usr/lib/gcc/x86_64-linux-gnu/9/include/bmi2intrin.h: In function ‘unsigned int _pdep_u32(unsigned int, unsigned int)’:
/usr/lib/gcc/x86_64-linux-gnu/9/include/bmi2intrin.h:48:10: error: ‘__builtin_ia32_pdep_si’ was not declared in this scope; did you mean ‘__builtin_ia32_dpps’?
   48 |   return __builtin_ia32_pdep_si (__X, __Y);
      |          ^~~~~~~~~~~~~~~~~~~~~~
      |          __builtin_ia32_dpps
/usr/lib/gcc/x86_64-linux-gnu/9/include/bmi2intrin.h: In function ‘unsigned int _pext_u32(unsigned int, unsigned int)’:
/usr/lib/gcc/x86_64-linux-gnu/9/include/bmi2intrin.h:55:10: error: ‘__builtin_ia32_pext_si’ was not declared in this scope; did you mean ‘__builtin_ia32_kxorsi’?
   55 |   return __builtin_ia32_pext_si (__X, __Y);
      |          ^~~~~~~~~~~~~~~~~~~~~~
      |          __builtin_ia32_kxorsi
/usr/lib/gcc/x86_64-linux-gnu/9/include/bmi2intrin.h: In function ‘long long unsigned int _bzhi_u64(long long unsigned int, long long unsigned int)’:
/usr/lib/gcc/x86_64-linux-gnu/9/include/bmi2intrin.h:64:10: error: ‘__builtin_ia32_bzhi_di’ was not declared in this scope; did you mean ‘__builtin_ia32_bsrdi’?
   64 |   return __builtin_ia32_bzhi_di (__X, __Y);
      |          ^~~~~~~~~~~~~~~~~~~~~~
      |          __builtin_ia32_bsrdi
/usr/lib/gcc/x86_64-linux-gnu/9/include/bmi2intrin.h: In function ‘long long unsigned int _pdep_u64(long long unsigned int, long long unsigned int)’:
/usr/lib/gcc/x86_64-linux-gnu/9/include/bmi2intrin.h:71:10: error: ‘__builtin_ia32_pdep_di’ was not declared in this scope; did you mean ‘__builtin_ia32_dppd’?
   71 |   return __builtin_ia32_pdep_di (__X, __Y);
      |          ^~~~~~~~~~~~~~~~~~~~~~
      |          __builtin_ia32_dppd
/usr/lib/gcc/x86_64-linux-gnu/9/include/bmi2intrin.h: In function ‘long long unsigned int _pext_u64(long long unsigned int, long long unsigned int)’:
/usr/lib/gcc/x86_64-linux-gnu/9/include/bmi2intrin.h:78:10: error: ‘__builtin_ia32_pext_di’ was not declared in this scope; did you mean ‘__builtin_ia32_kxordi’?
   78 |   return __builtin_ia32_pext_di (__X, __Y);
      |          ^~~~~~~~~~~~~~~~~~~~~~
      |          __builtin_ia32_kxordi
In file included from ./include/pgm/pgm_index_variants.hpp:19,
                 from examples/multidimensional.cpp:15:
./include/pgm/piecewise_linear_model.hpp: At global scope:
./include/pgm/piecewise_linear_model.hpp:31:73: note: #pragma message: Compilation with -fopenmp is optional but recommended
   31 | #pragma message ("Compilation with -fopenmp is optional but recommended")
      |     
~~~

**Comment by shiyunya** [comment]
$ g++ examples/multidimensional.cpp -std=c++17 -I./include -o `multidimensional`
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/include/immintrin.h:105,
                 from ./include/pgm/morton_nd.hpp:41,
                 from ./include/pgm/pgm_index_variants.hpp:18,
                 from examples/multidimensional.cpp:15:
/usr/lib/gcc/x86_64-linux-gnu/9/include/bmi2intrin.h: In function ‘unsigned int _bzhi_u32(unsigned int, unsigned int)’:
/usr/lib/gcc/x86_64-linux-gnu/9/include/bmi2intrin.h:41:10: error: ‘__builtin_ia32_bzhi_si’ was not declared in this scope; did you mean ‘__builtin_ia32_bsrsi’?
   41 |   return __builtin_ia32_bzhi_si (__X, __Y);
      |          ^~~~~~~~~~~~~~~~~~~~~~
      |          __builtin_ia32_bsrsi
/usr/lib/gcc/x86_64-linux-gnu/9/include/bmi2intrin.h: In function ‘unsigned int _pdep_u32(unsigned int, unsigned int)’:
/usr/lib/gcc/x86_64-linux-gnu/9/include/bmi2intrin.h:48:10: error: ‘__builtin_ia32_pdep_si’ was not declared in this scope; did you mean ‘__builtin_ia32_dpps’?
   48 |   return __builtin_ia32_pdep_si (__X, __Y);
      |          ^~~~~~~~~~~~~~~~~~~~~~
      |          __builtin_ia32_dpps
/usr/lib/gcc/x86_64-linux-gnu/9/include/bmi2intrin.h: In function ‘unsigned int _pext_u32(unsigned int, unsigned int)’:
/usr/lib/gcc/x86_64-linux-gnu/9/include/bmi2intrin.h:55:10: error: ‘__builtin_ia32_pext_si’ was not declared in this scope; did you mean ‘__builtin_ia32_kxorsi’?
   55 |   return __builtin_ia32_pext_si (__X, __Y);
      |          ^~~~~~~~~~~~~~~~~~~~~~
      |          __builtin_ia32_kxorsi
/usr/lib/gcc/x86_64-linux-gnu/9/include/bmi2intrin.h: In function ‘long long unsigned int _bzhi_u64(long long unsigned int, long long unsigned int)’:
/usr/lib/gcc/x86_64-linux-gnu/9/include/bmi2intrin.h:64:10: error: ‘__builtin_ia32_bzhi_di’ was not declared in this scope; did you mean ‘__builtin_ia32_bsrdi’?
   64 |   return __builtin_ia32_bzhi_di (__X, __Y);
      |          ^~~~~~~~~~~~~~~~~~~~~~
      |          __builtin_ia32_bsrdi
/usr/lib/gcc/x86_64-linux-gnu/9/include/bmi2intrin.h: In function ‘long long unsigned int _pdep_u64(long long unsigned int, long long unsigned int)’:
/usr/lib/gcc/x86_64-linux-gnu/9/include/bmi2intrin.h:71:10: error: ‘__builtin_ia32_pdep_di’ was not declared in this scope; did you mean ‘__builtin_ia32_dppd’?
   71 |   return __builtin_ia32_pdep_di (__X, __Y);
      |          ^~~~~~~~~~~~~~~~~~~~~~
      |          __builtin_ia32_dppd
/usr/lib/gcc/x86_64-linux-gnu/9/include/bmi2intrin.h: In function ‘long long unsigned int _pext_u64(long long unsigned int, long long unsigned int)’:
/usr/lib/gcc/x86_64-linux-gnu/9/include/bmi2intrin.h:78:10: error: ‘__builtin_ia32_pext_di’ was not declared in this scope; did you mean ‘__builtin_ia32_kxordi’?
   78 |   return __builtin_ia32_pext_di (__X, __Y);
      |          ^~~~~~~~~~~~~~~~~~~~~~
      |          __builtin_ia32_kxordi
In file included from ./include/pgm/pgm_index_variants.hpp:19,
                 from examples/multidimensional.cpp:15:
./include/pgm/piecewise_linear_model.hpp: At global scope:
./include/pgm/piecewise_linear_model.hpp:31:73: note: #pragma message: Compilation with -fopenmp is optional but recommended
   31 | #pragma message ("Compilation with -fopenmp is optional but recommended")
      |

**Comment by shiyunya** [comment]
画像
![tmp](https://user-images.githubusercontent.com/53427851/119118264-01d2fd80-ba65-11eb-89b1-b231fbd562c1.png)

**Comment by baycedar** [comment]
これですが，手元のWSLで試したらいけました．clone後，以下のコマンドを打っています．

```bash
cd 202104-PGMindex-suzuki
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make -j
./examples/example_multidimensional
```

以下が実行環境です（コマンドを区別するために行頭に`$`を入れています）．

```bash
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
$ g++ --version
g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
$ cmake --version
cmake version 3.16.3
```

**Comment by shiyunya** [comment]
ありがとうございます！
コンパイルできました

（cmakeは設定を書いておくといいかんじのMakefileを作ってくれるコマンドなんですね）
